import = ["~/.config/alacritty/themes/coolnight.toml"]

[cursor.style]
shape = "Block"
blinking = "Always"

[font]
size = 16.0

[font.normal]
family = "0xProto Nerd Font"

[window]
decorations = "full"
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.8

[window.padding]
x = 5
y = 5
