[cursor]
blink_timeout = 0

[cursor.style]
shape = "Underline"
blinking = "Always"

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "none"
startup_mode = "maximized"
dynamic_padding = true

[general]
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]
