import = ["~/.config/alacritty/themes/coolnight.toml"]

[cursor]
blink_timeout = 0

[cursor.style]
shape = "Underline"
blinking = "Always"

[font]
size = 16.0

[font.normal]
family = "MesloLGS NF"

[window]
decorations = "none"
startup_mode = "maximized"
dynamic_padding = true
