import = ["~/.config/alacritty/themes/coolnight.toml"]

[cursor]
blink_timeout = 0

[cursor.style]
shape = "Block"
blinking = "Always"

[font]
size = 16.0

[font.normal]
family = "0xProto Nerd Font"

[window]
decorations = "none"
startup_mode = "maximized"
dynamic_padding = true
opacity = 0.5

[window.padding]
x = 5
y = 5
